---
# ESPHome Core configuration
#
# Sets the defaults for the main core configuration of ESPHome devices.
#
# https://esphome.io/components/esphome.html
#
name: "${system_name}"
comment: "${device_description}"
